### ISSUE TITLE
Mod not working serverside on last forge 1.18.1

### ISSUE THREAD

**Issue by noxnoire** [c-massie/ItemCopy#1]
no extra mods needed , it just doesnt let the server properly load heres the log if you need it
[latest.log](https://github.com/c-massie/ItemCopy/files/8210577/latest.log)
steps to reproduce , 
1:download forge installer , 
2:install last 1.18.1
3:add the mod
4:run it
,log points to line 29 of itemcopy.java , mod works on client btw
same error on 1.18.2 server

**Comment by c-massie** [comment]
Thank you for the report!

I'm busy right now with IRL stuff, but I'll fix this once I'm finished.

**Comment by c-massie** [comment]
Fixed - Registering events in ClientPlayerNetworkEvent (client-side events which I was using to listen to the player joining or leaving worlds) crashes dedicated servers instead of just not being fired.
